### ISSUE TITLE
How to get sand from the composter?

### ISSUE THREAD

**Issue by 991200448** [jsorrell/skyblock#1]
I try to get the sand/redsand from the composter,but I get the dirt.I am no sure is the sand only get at a time from a wandering trader?

**Comment by QPCrummer** [comment]
You most likely have to be in a desertish biome to get sand or in a mesa biome to get redsand.

**Comment by jsorrell** [comment]
@QPCrummer is correct. It's based on the default surface block of the biome the composter is in. So in sandy biomes like deserts and beaches you'll get sand and in badlands type biomes you'll get red sand.
