### ISSUE TITLE
suggestion to make a more elaborate advancement progression line

### ISSUE THREAD

**Issue by h3oCharles** [jsorrell/skyblock#12]
I've seen the custom advancements that this skyblock adds, and they seem somewhat lackluster, which got me a bit disappointed. I might be biased because I used to play a lot of modded Minecraft with quest lines

my suggestion is to make an advancement line that can guide players or give hints as to what to do to make progress

some advancements could include (and are not limited to):
- hints to new mechanics that have been added here
- instructions to execute the trigger command
- hint some unorthodox ways of getting stuff, like curing villagers using weakness potions thrown by witches (not everyone would figure that out, and could be a major choke point)
- acquiring each item from modified wandering trader trades

I'm also interested in collaborating in making this, but only on the theory level, using an online flow chart generator that can be easily shared, I have no idea how advancements are made in-game

**Comment by jsorrell** [comment]
I agree the advancements were an afterthought and can use improvement. Design over implementation is the main reason there aren't more. I'd be happy for your help.

**Comment by h3oCharles** [comment]
Design? what do you mean? the menu being too small? i did some research and managed to find some mods regarding that
https://www.curseforge.com/minecraft/mc-mods/advancements-enlarger
https://www.curseforge.com/minecraft/mc-mods/advancementinfo

**Comment by jsorrell** [comment]
I meant I can code the advancements; I just need ideas.

**Comment by h3oCharles** [comment]
First attempt at making some progress, let me know what you think so far
https://drive.google.com/file/d/1B5aHAFWejp8FpeOgSewuBVLY8MWkfHQh/view?usp=sharing
