### ISSUE TITLE
[Suggestion] An idea of acquiring ancient debris

### ISSUE THREAD

**Issue by zhguyu** [jsorrell/skyblock#17]
It's definitely great to have a way to obtain ancient debris in skyblock playthrough, but one thing that bothers me a little bit is the way how it is obtained. Getting 'Hero of the village' buff in the nether, to my understanding, involves: 1) setup a village in nether; 2) find a pillager outpost structure and get the Bad Omen effect from a raid captain; 3) return to the village and fight; 4) win the fight.
The problem is, none of the above actions has a vanilla connection with nether nor ancient debris, so I've been thinking about an alternative approach that utilises a mob that wouldn't appear in a normal skyblock playthrough: piglin brute. Basically, make piglin brute spawnable in the bastion remnant structure (the spawn chance can mimic that of the wither skeleton in a nether fortress), and make it rarely drop an ancient debris when killed by player (again, the drop chance can mimic that of a wither skeleton dropping its skull).
Apparently, this approach does have a certain level of connection with ancient debris itself: ancient debris and netherite ingots can generate in the treasure chest of bastion remnants. In the mean time, this makes use of piglin brutes and bastion remnants, both of which were completely useless in normal skyblock playthroughs. Thus it won't break the vanilla feel.

**Comment by jsorrell** [comment]
This change was included in 1.3.1. Thanks for the suggestion.
