### ISSUE TITLE
Merry Christmas！About Sweet Berries

### ISSUE THREAD

**Issue by Noopig** [jsorrell/skyblock#18]
Hello, jsorrell.
Someone I talked to the other day asked me how to get Sweet Berries.
I took the time to do some research, and neither original Minecraft nor SkyBlock has a proper way to access it. 
That's all.
Merry Christmas!

**Comment by jsorrell** [comment]
This is fixed in 3.1.0 -- Foxes can now spawn holding Sweet Berries.
