### ISSUE TITLE
Will 1.18 be supported in the future? 

### ISSUE THREAD

**Issue by rongke1997** [jsorrell/skyblock#20]
Will it be upgraded to 1.18 ？

**Comment by jsorrell** [comment]
I'll look at updating it to 1.18 if I find time this week.

**Comment by MSC1309** [comment]
Please hurry up. There will not be so many light sources in 1.18. It will be very convenient at an early stage

**Comment by TheDoddsy** [comment]
https://github.com/openana/skyblock/releases
Found this fork of it, and it seems to work

**Comment by jsorrell** [comment]
Sorry for the delay. A 1.18 release is now posted [here](https://github.com/jsorrell/skyblock/releases).
