### ISSUE TITLE
How to get soul soil?

### ISSUE THREAD

**Issue by PengCheong** [jsorrell/skyblock#21]
I'm trying to get some smooth basalt for budding Amethysts, but how should I get some soul soil? As minecraft wiki says soul soil can only be generated naturally, and it is not in the barter with piglin.

**Comment by jsorrell** [comment]
You can make soul campfires with soul sand (from bartering), but if you break them without silk touch they drop soul soil.
[wiki link](https://minecraft.fandom.com/wiki/Campfire#Converting_soul_sand_to_soul_soil)
