### ISSUE TITLE
about the piglinsSpawningInBastions

### ISSUE THREAD

**Issue by Noopig** [jsorrell/skyblock#23]
Monsters often brush under or outside platforms and fall directly into the void.
Looks like a Carpet problem.
There are still ways to build spawns, but I think you should know this.

**Comment by Noopig** [comment]
Monsters often spawn in the void and fall to their death.

**Comment by zhguyu** [comment]
> Monsters often spawn in the void and fall to their death.

Do you mean they spawn in the entire bastion structure even without a platform and then directly fall into the void? That's interesting to know.

**Comment by Noopig** [comment]
> > Monsters often spawn in the void and fall to their death.
> 
> Do you mean they spawn in the entire bastion structure even without a platform and then directly fall into the void? That's interesting to know.

No，There is a platform nearby, spawns will not spawn on the platform after spawning

**Comment by jsorrell** [comment]
This is due to the fact that Minecraft allows Piglin Brutes are allowed to spawn in mid air. I assume Mojang never gave them spawn restrictions because they're only supposed to spawn on world gen. Will release a fix shortly.

**Comment by jsorrell** [comment]
I opened an [issue](gnembon/fabric-carpet#1335) for the Carpet mod but this should be fixed in 3.1.1.
