### ISSUE TITLE
Cannot craft Blast Furnace in release 1.18.1-3.1.2

### ISSUE THREAD

**Issue by tylzh97** [jsorrell/skyblock#25]
I'm pretty sure that i have loaded the datapack:
I can craft [Netherrack] with 9 [Rotten Flesh], and get a diamond with [anvil] and [64 coal blocks].

But [Blast Furnace] cannot craft with [Prismarine Brick]. 

![](https://s3.bmp.ovh/imgs/2022/02/1dee8438dc3efb0e.png)
![](https://s3.bmp.ovh/imgs/2022/02/403be8ea27df9436.png)
![](https://s3.bmp.ovh/imgs/2022/02/7733b3d5b69161b4.png)

**Comment by jsorrell** [comment]
As of 3.1.0, the recipe to get a Blast Furnace from Prismarine was removed because it was not necessary. Gold can be obtained by converting Pigs to Zombified Piglins with lightning. A lightning rod is obtainable using copper from a Drowned farm.

**Comment by tylzh97** [comment]
I got that, thanks!
