### ISSUE TITLE
Blast furnace formulation cannot be used in 1.18.1

### ISSUE THREAD

**Issue by Guodo** [jsorrell/skyblock#26]
Blast furnace formulation cannot be used in 1.18.1

**Comment by zhguyu** [comment]
That recipe is already deprecated. The proper way to get gold now is to wait for pigs to spawn on the grass blocks, breed them to get about 300 pigs, craft a lightning rod out of copper acquired from a drowned farm, let lightning strike on the pigs to turn them into zombified piglins, and kill them to get gold.

**Comment by zhguyu** [comment]
Also make sure to use fireproof building blocks when you do this.
