### ISSUE TITLE
1.18.2 No SLF4J Providers

### ISSUE THREAD

**Issue by razgriz5000** [jsorrell/skyblock#27]
Fails to load in 1.18.2 with the below error.  Hopefully it is a simple fix to get it to work with 1.18.2.  

`SLF4J: No SLF4J providers were found. SLF4J: Defaulting to no -operation (NOP) logger implementation SLF4J: See http://www.slf4j.org/codes/html#noProviders for further details.  `

**Comment by jsorrell** [comment]
A 1.18.2 version is now available
