### ISSUE TITLE
suggestion to be able to get cave spiders

### ISSUE THREAD

**Issue by bob-a-tea** [jsorrell/skyblock#29]
there is currently no way to get cave spiders, so I would appreciate it a lot of we could have a way to get cave spiders. Maybe a way to generate a spawner block similar to the budding amethyst block. Thanks!

**Comment by jsorrell** [comment]
I think cave spiders are the only unobtainable mob in 1.18, with silverfish spawners being generated, elder guardians created through lighting, and piglin brutes spawning in bastions, so maybe it would be good to add a way to get them. Generating spawners seems too overpowered to me though -- you could easily put a large number next to each other.

Maybe cave spiders could spawn in abandoned mineshafts? Or in cave biomes?

**Comment by bob-a-tea** [comment]
Oh yeah, spawner blocks are totally overpowered now that I think about it. Perhaps spiders convert to cave spiders after being in cobwebs in abandoned mineshafts? Like if a spider is in a cobweb block which is in a mineshaft, it will become a cave spider. Or spiders with the poison effect could also become cave spiders. Thanks for considering the cave spider situation man!

**Comment by jsorrell** [comment]
Spiders aren't normally affected by poison or cobwebs. The cobweb idea is interesting, but it doesn't make much sense to me "logically" (Minecraft logic). How does a cobweb convert a spider? But the poison idea does. Maybe spiders can convert when fed a poisonous potato (giving a use to the perennially useless)? Or when killed by a pufferfish (like villager -> zombie villager)? The idea being they're imbued with poison or whatever.

**Comment by jsorrell** [comment]
This is implemented in 3.2.0
