### ISSUE TITLE
Cannot Update to 1.18.1/2

### ISSUE THREAD

**Issue by SyrileDemonthyst** [jsorrell/skyblock#30]
I last played this Skyblock in 1.17.1. Once I tried to update my work to 1.18.2, the Skyblock resource pack says that it is made for a newer version of Minecraft. But I have updated all of my mods to the newest version. When that failed to work, I restarted and installed them all again, using only Fabric API, Carpet and Skyblock and the resource pack still shows that it is made for a newer version.

After giving up on that, I attempted to use 1.18.1 instead. It shows that the resource pack is valid but when I try to load the world, I get an error message of

![image](https://user-images.githubusercontent.com/103155199/162096358-93258b4a-30d0-4f34-91ee-143d28d0588d.png)

I have tried entering in safemode but that does not work. I have tried many methods of updating files, various combinations of files and relaunching but nothing will let me actually load the world. I am not sure what else to do at this point. I searched for anyone having this issue but I could not find anything online. However, I had multiple friends try to create a new world with 1.18.2 and they all get the same message that it was made for a newer version of Minecraft. It seems that neither method will work.

**Comment by jsorrell** [comment]
This has to do with the 1.17->1.18 Vanilla behavior of replacing the Bedrock with Deepslate and moving it down. This is the only time already generated chunks are ever altered. Fixing this now.

**Comment by SyrileDemonthyst** [comment]
> 

I assumed it was something to do with that but I was not sure. Thank you. :)

**Comment by jsorrell** [comment]
Seeing as this is a unique issue and fixing would require some ugly mixins into datafixers, its probably easiest to just upgrade your world manually. It just requires simple edits to the NBT of the `level.dat` file.

### To Update from 1.17.1 to 1.18.2

- ***Backup your World!***
- Open the level.dat for your world in a NBT editor such as NBTExplorer or [WebNBT](https://irath96.github.io/webNBT/)
- Under `Data -> WorldGenSettings -> dimensions -> minecraft:overworld -> generator -> biome_source`
  - delete the `large_biomes` tag and the `seed` tag
  - change `type` from `minecraft:vanilla_layered` to `minecraft:multi_noise`
  - add a string tag with the name `preset` and the value `minecraft:overworld`
- Under `Data -> Version`
  - Change `id` from `2730` to `2975`
  - Change `Name` from `1.17.1` to `1.18.2`
- Change `Data -> DataVersion` from `2730` to `2975`

The world should then load fine in 1.18.2. Let me know if you have any issues.

**Comment by Noopig** [comment]
Thanks guys, I will inform the method to my Bilibili account

**Comment by SyrileDemonthyst** [comment]
>  ### To Update from 1.17.1 to 1.18.2

It seems to work just fine.
Not sure if it matters at all on your end but it does still say in the resource pack that the Skyblock pack is made for a newer version of Minecraft. However, in the test version I copied from the original, it appears to work perfectly. Thank you very much. :)

I will close this issue in a few hours if it is not already closed, just in case anyone else is having a similar problem. Or you can close it earlier if you want.
