### ISSUE TITLE
Tall Grass and Large Fern Unobtainable

### ISSUE THREAD

**Issue by themdlchemist** [jsorrell/skyblock#33]
I noticed that there is no way to get tall grass or large fern in item form in this mod. While completely pointless, I think that this could be fixed by letting Endermen pick them up. If you then killed an enderman that is holding tall grass/large fern, it will drop it as an item.

**Comment by jsorrell** [comment]
There's no way to obtain them in vanilla survival though, right? This mod only provides ways of getting things that vanilla survival does.

**Comment by themdlchemist** [comment]
You can rarely find tall grass in savannah village houses and large ferns in taiga village houses.

**Comment by jsorrell** [comment]
I like this idea. But it looks like Enderman aren't good at handling double-block items. They can pick them up, but the items render in their hands incorrectly and they get deleted if they try to place them. I'll look into finding a solution but it might have to wait for the next update.

**Comment by themdlchemist** [comment]
Hello, would you accept a merge request if I were to fix Endermen picking up 2 tall blocks?

**Comment by jsorrell** [comment]
I already implemented this in the 1.19 branch (only the server side fix, not rendering fix). I'll release it for 1.18 though if you want it sooner.

**Comment by themdlchemist** [comment]
Oh, I thought that you meant the next skyblock update, not 1.19.

**Comment by jsorrell** [comment]
Released in 1.18.2-3.2.4
