### ISSUE TITLE
Any chance of adding an opt-in feature for having wandering trader sell lava buckets?

### ISSUE THREAD

**Issue by anonaddict** [jsorrell/skyblock#34]
I personally prefer that way of obtaining it but I can see why other people might prefer gifts

**Comment by jsorrell** [comment]
Added this in 1.18.2-3.2.1

**Comment by anonaddict** [comment]
> Added this in 1.18.2-3.2.1

Thank you so much

**Comment by Noopig** [comment]
> 在 1.18.2-3.2.1 中添加了此内容

Thank you
