### ISSUE TITLE
Can we fish for bamboo and cocoa beans in the sparse jungle?

### ISSUE THREAD

**Issue by Noopig** [jsorrell/skyblock#35]
Minecraft 1.18.2
Skyblock and datapacks  V1.18.2-3.1.3

In the original, this is what I caught in the sparse jungle fishing for trash.
[image](https://github.com/Noopig/my-picture/blob/main/%E5%8E%9F%E7%89%88%E7%A8%80%E7%96%8F%E4%B8%9B%E6%9E%97.png)
But sparsely bushfishing in the Skyblock yielded a very different harvest.
[image](https://github.com/Noopig/my-picture/blob/main/skyblock%E7%A8%80%E7%96%8F%E4%B8%9B%E6%9E%972.png)
[image](https://github.com/Noopig/my-picture/blob/main/skyblock%E7%A8%80%E7%96%8F%E4%B8%9B%E6%9E%971.png)
So should we be able to catch bamboo and cocoa beans in the sparse jungle？

**Comment by jsorrell** [comment]
Fixed in 3.2.2
