### ISSUE TITLE
Outer End Gateways (the ones that send you to the obby platform) should generate (and I also suggest the ability to turn off generation of magma spawners)

### ISSUE THREAD

**Issue by bob-a-tea** [jsorrell/skyblock#36]
Hello, and also I'd like to apologize for making another suggestion. I know I've already made one earlier though, and I need to thank you for implementing it.
I suggest that the outer end gateways, the ones that randomly generate throughout the outer end, should spawn in the Skyblock world generation. Bedrock is already extremely limited, and it would be kind of sad to have to sacrifice the exit end portal or one of the 20 main end gateways for a wither killer. Wither rose farms would also be a lot better with outer end gateways. I feel like it'd fit the "generate almost nothing except for a few things" theme this mod has.
Also, I feel like it'd make sense to be able to disable magma spawner generation and if you implement end gateways, those as well, with a /skyblock command.
Thank you for your time!

**Comment by jsorrell** [comment]
Implemented in 3.2.2
