### ISSUE TITLE
composter suggestion 

### ISSUE THREAD

**Issue by razgriz5000** [jsorrell/skyblock#4]
Is it possible to get both bonemeal and dirt, sand, etc out of a composter?  Early game getting bonemeal back from composting can be just as valuable as getting extra dirt and sand.  I do not like the idea of having to keep switching the setting during a playthrough.

**Comment by jsorrell** [comment]
Usually it's best to just use skeletons, so I don't think this is necessary but I can add an option if you want. Do you think it should make both bonemeal + dirt etc at the same time or have some trigger like sitting on top of a certain block?

**Comment by razgriz5000** [comment]
I think having it as a different option to allow both bonemeal and dirt drop would be good.  I am not sure what the best trigger would be.  Is it possible to detect if the composter is redstone powered?  by say a lever? Unpowered gives bonemeal and powered gives dirt.  A different option could be that the dirt is a chance, not a guarantee.  

You are probably right that for most playthroughs just getting bonemeal from bones will suffice.  The only time it is problematic is if the start is in the nether where you might not be close enough to a soul sand valley.

**Comment by jsorrell** [comment]
Implemented in latest release
