### ISSUE TITLE
[Suggestion] Craft Furnaces with Prismarine

### ISSUE THREAD

**Issue by Matt-Hurd** [jsorrell/skyblock#7]
In 1.17, Drowned no longer drop gold. This makes the progression incredibly tedious in order to get golden apples for villagers. The current method would be farming for 16 emeralds from foxes, which would take a very long time, even with enabling the composter improvements.

For my world, I've added `minecraft:prismarine` to `tags/items/stone_crafting_materials.json` in order to allow it to be used to craft a furnace. This allows the gold armor drops from zombies to be smelted down after creating a guardian farm.

By adding it to `stone_crafting_materials`, the only recipes that are affected are furnaces and brewing stands. Optionally it could be enabled to allow for crafting stone tools, but I opted to have a minimal change to unblock progression.

**Comment by jsorrell** [comment]
I like the way this progression works, requiring Prismarine to replace the early Drowned farm. My only problem is this gives access to all furnace recipes way earlier, which is a pretty big change from Vanilla. I opted to instead add a recipe for a blast furnace using Prismarine, which only really gives access to smelting down gold tools, keeping the changes as minimal as possible.
