### ISSUE TITLE
Glow Berries are unattainable

### ISSUE THREAD

**Issue by Matt-Hurd** [jsorrell/skyblock#8]
The advancement says to get Glow Berries from a Fox, however Foxes do not spawn with or randomly find Glow Berries. They just pick them off of existing cave vines.

Glow berries are interesting for progression in that they're an alternative source of dirt generation via moss blocks, rather than going through the coarse dirt route. You can convert cave vines to moss blocks, then grow azalea on top of them to create rooted dirt, which can be converted to normal dirt.

**Comment by jsorrell** [comment]
I forgot to add it to the readme and forgot to add a setting for it (I'll release a version shortly with the setting), but one of the mod features is that foxes that spawn with an item have a 20% chance for it to be a glow berry, similar to wheat or leather.

**Comment by jsorrell** [comment]
This feature is now documented and is disable-able in 3.0.1
